name: Update README

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: charmbracelet/readme-scribe@master
        env:
          WAKATIME_URL: ${https://hackatime.hackclub.com/api/hackatime/v1}
          WAKATIME_API_KEY: ${5baa0e84-1f8e-42eb-9120-f56391772c67}
        with:
          template: "README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${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}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
